### ISSUE TITLE
Update action to Node 20

### ISSUE THREAD

**Issue by enekodr** [buildwith-ionos/deploy-to-ionos-action#3]
As shown in this [GitHub article](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/), Node 16 will be deprecated by Spring 2024. This alert is shown after setting up Deploy Now GitHub Action in a repository:

<img width="1074" alt="Captura de pantalla 2024-02-09 a las 3 12 09" src="https://github.com/ionos-deploy-now/deploy-to-ionos-action/assets/25287536/db1d6e06-1cbb-4348-9f06-ba3d57f8384e">

**Comment by ionos-deploy-now-support** [comment]
Hey @enekodr, 
thank you for your hint. We are working on updating the actions to at least 20.11.0 in time. 

All the best
Your Deploy Now Team
